name: GitHub Actions for java-rest-controller
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Docker:
    name: Create and push Docker Image
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Creating Docker Image"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jffelippe/react-app:latest